export const items = [
    {
        id: 0,
        name: "pizza",
        category: "entree",
        price: "$14.99",
        desc: "14 inch pizza with house made red sauce and your choice of up to 4 toppings.",
        src: "./img/pizza.jpg",
    },
    {
        id: 1,
        name: "calzone",
        category: "entree",
        price: "$11.99",
        desc: "mozzarella, house red sauce, ricotta cheese, and your choice of up to 4 toppings",
        src: "./img/calzone.jpg",
    },
    {
        id: 2,
        name: "sausage sandwich",
        category: "entree",
        price: "$9.99",
        desc: "fresh made in house sausage on fresh italian hoagie bun, served with mozzarella cheese and green chilis.",
        src: "./img/sausage sandwich.jpeg",
    },
    {
        id: 3,
        name: "homemade spaghetti",
        category: "entree",
        price: "$10.99",
        desc: "spagetti made in house fresh everyday. comes with choice of two meatballs, two sausage, or one of each",
        src: "./img/spaghetti.jpg",
    },
    {
        id: 4,
        name: "cannoli",
        category: "dessert",
        price: "$5.99",
        desc: "3 italian cannoli's with homemade cannoli cream",
        src: "./img/cannoli.jpg",
    },
    {
        id: 5,
        name: "cookies",
        category: "dessert",
        price: "$2.99",
        desc: "choice of three cookies. choose between chocolate chip, sugar, or double chocolate fudge",
        src: "./img/cookies.jpg",
    },
    {
        id: 6,
        name: "tiramisu",
        category: "dessert",
        price: "$6.99",
        desc: "fresh tiramisu made from scratch every week",
        src: "./img/tiramisu.jpg",
    },
    {
        id: 7,
        name: "gibson",
        category: "drink",
        price: "$7.99",
        desc: "london dry gin, dry vermouth, organe bitters, cocktail onion",
        src: "./img/gibson.jpg",
    },
    {
        id: 8,
        name: "old fashion",
        category: "drink",
        price: "$7.99",
        desc: "bourbon whiskey, demerara sugar, bitters, citrus oil",
        src: "./img/old fashion.jpg",
    },
    {
        id: 9,
        name: "manhattan",
        category: "drink",
        price: "$7.99",
        desc: "rye whiskey, sweet vermouth, aromatic bitters, cherry",
        src: "./img/manhatten.jpg",
    },
];
